### ISSUE TITLE
開発環境の構築がうまくいかない。

### ISSUE THREAD

**Issue by 4416kidr** [ARCircle/Kojirer#10]
# 開発環境の構築がうまくいかない

## 主な作業内容

1. `.devcontainer`フォルダに`docker-compose.yml`を移行

## 開発環境の構築方法

1. docker desktopを起動する
2. `code kojirer` でvscodeを起動する
3. vscodeに`dev containers` という拡張機能を入れる
   1. [ここ（zenn）](https://zenn.dev/greendrop/articles/8bf88aad068f7d)とかを見ると参考になると思います
4. 左下の「><」みたいなマークをクリックして、「コンテナーで再度開く（英語: open container?）」で起動
   1. 初回起動時におそらく、起動構成どうするって聞かれる。ワークスペースでもフォルダでもどちらでもよいと思う（多分）
6. `.env`のPOSTGRES系の4変数を`.devcontainer/docker-compose.yml`と合わせる
   1. URLの変数は上記3変数を参照して、適切にベタ打ちする
   2. `.env`をどう整理するかは議論中のため、今後変更される可能性がある
7. `npm run migrate:dev`を実行すると、以下のようなエラーが出る。

    ```txt
    node ➜ /workspaces/Kojirer (fix/use-dev-container) $ npm run migrate:dev

    > kojirer@0.1.0 migrate:dev
    > npm run migrate:exe


    > kojirer@0.1.0 migrate:exe
    > ./node_modules/.bin/env-cmd -f .env npm run migrate:exe    -w packages/backend


    > backend@0.1.0 migrate:exe
    > npx prisma migrate dev

    Prisma schema loaded from prisma/schema.prisma
    Datasource "db": PostgreSQL database "postgres", schema "public" at "db:5432"

    Already in sync, no schema change or pending migration was found.

    Running generate... (Use --skip-generate to skip the generators)
    Error: 
    You don't have any models defined in your schema.prisma, so nothing will be generated.
    You can define a model like this:

    model User {
    id    Int     @id @default(autoincrement())
    email String  @unique
    name  String?
    }

    More information in our documentation:
    https://pris.ly/d/prisma-schema

    npm ERR! Lifecycle script `migrate:exe` failed with error: 
    npm ERR! Error: command failed 
    npm ERR!   in workspace: backend@0.1.0 
    npm ERR!   at location: /workspaces/Kojirer/packages/backend
    ```

5. メッセージにあるように`packages/backend/prisma/schema.prisma`に以下の内容を追記

    ```txt
    model User {
    id    Int     @id @default(autoincrement())
    email String  @unique
    name  String?
    }
    ```

8. `npm run migrate:dev`を実行すれば、うまくいきそうな雰囲気を感じるので、`Ctrl+C`で中断する
   1. 以降の部分に関しては議論中または作業中である

**Comment by tenk-9** [comment]
聴いてはいたものの，あまりよくわかってないので，手順が確定したら[ドキュメント](https://github.com/ARCircle/Kojirer?tab=readme-ov-file#how-to-start-develop)にまとめておいて欲しいです．

**Comment by 4416kidr** [comment]
いったん、ここに手順を記載しました。
まだ環境構築は完成していないので、完成し次第README.mdに反映されると思います。

**Comment by 4416kidr** [comment]
拡張機能について追記しました
