### ISSUE TITLE
指定したIDの丼の調理状態を変更するAPIの実装

### ISSUE THREAD

**Issue by tenk-9** [ARCircle/Kojirer#16]
要件は次の通りです．
- created: 3/15 11:15
- mod: 3/28 19:15, `調理ステータス`->`調理状態`

## 概要
丼の`調理状態`を変更するAPIの要件です．
丼のid`dons.id`と遷移先の調理状態コード(`dons.status`)をパラメータとするリクエストを投げ，成功したか否かを返して欲しいです．
このAPIを呼び出す端末とその目的は次の2例を想定しています．
- 調理場の端末
  - 料理係が，調理が終了した丼に対応するボタンを押し，`調理中`から`呼び出し中`へ状態を変更します
  - #15 のAPIと関連し，調理場の端末からは，押したボタンに対応する丼は消えます．
- 受け渡し口の端末
  - 受け渡し担当者が，客への受け渡しが完了した丼に対応するボタンを押し，`呼び出し中`から`受け渡し完了へ状態を変更します．
  - #15 のAPIと関連し，受け渡し口の端末からは，押したボタンに対応する丼は消えます．
#### 調理状態について
`dons.status`の値です．ここでは，
`1`（調理中）->`2`（呼び出し中）->`3`（受け渡し済み）
の3段階と仮定します．

### リクエスト
- PUT(id, status)の形式です．
- パラメータは`id`と`status`の二つです．
- エンドポイント名や実装（クエリパラメータ or パスパラメータ or else）はお任せします．
- 例えばエンドポイントは次のようなものが考えられます．
  - `koujirer/setDonStatus?id=12302&status=2`
  - `koujirer/updateDonStatus/12302&status=3`
#### 成功時
- 成功したことがわかるステータスコードを持ったレスポンスを返して欲しいです．
- BODYは空で構いません
- 余裕があれば調理状態の変更に成功した丼の情報（#15のレスポンスで期待するものと同様）を返してください（優先度，必要さはかなり低いです）．
#### 失敗時
- 簡単な失敗理由をBODYに含めたレスポンスを返して欲しいです．
### 参考資料
- [用語定義](https://github.com/ARCircle/Kojirer/discussions/9#discussioncomment-8784803)
- [DBスキーマ](https://www.notion.so/DB-4d6845cc5574443d86a8c9442d2f655b?pvs=4#56e4975ccaeb42d4b248a780629508cd)（3/14参照）
- [草案（画像，④）](https://github.com/ARCircle/Kojirer/discussions/9#discussioncomment-8787404)

**Comment by Atotti** [comment]
> 丼のiddons.idと遷移先のステータスコード(dons.status)

> 成功したことがわかるステータスコードを持ったレスポンスを返して欲しいです．

上は調理ステータスで下はHTTP レスポンスステータスコードですか？

**Comment by tenk-9** [comment]
> > 丼のiddons.idと遷移先のステータスコード(dons.status)
> 
> > 成功したことがわかるステータスコードを持ったレスポンスを返して欲しいです．
> 
> 上は調理ステータスで下はHTTP レスポンスステータスコードですか？

そうです．紛らわしくてすみません．
語句を修正しました（`調理ステータス`->`調理状態`）．

**Comment by Atotti** [comment]
雑メモ

```yaml
put:
  description: donの調理状態を更新する
  requestBody:
    content:
      application/json:
        schema:
        type: object
        properties:
       - donIid: integer
           format: int32
        afterStatus: integer
           format: int32
      requried:
       - donId
       - afterStatus
```
