### ISSUE TITLE
オプションの量と対応する数値の辞書を取得するAPIの実装

### ISSUE THREAD

**Issue by tenk-9** [ARCircle/Kojirer#17]
要件は次の通りです．この API が必要か否かについては議論の余地があると思います（see: **議論**）．

- created: 3/15 16:30
- edited: 3/17 21:40, 体裁を修正

## 概要

options の量と，それに対応する数値が取得できる API です．
oprions の量として考えられるのは

-   無し
-   少なめ
-   普通
-   ちょいマシ
-   マシ
-   マシマシ

等ですが，これらが表す量は数値にマッピングされて DB に格納されることになっています．
担当者が操作する端末上では自日本語の単語で表示したいです．が，注文の新規作成をする API や，丼の値段を取得する API 等でこれらの量がパラメータとなり，数値で送信する必要があります．
従って，量を表す日本語を key，DB 上での数値を value とするような，対応付けができる辞書が欲しいです．

#### 議論

そもそもこういった対応情報は環境変数みたいなものなので，API として取得できるようにするべきか否かは議論の余地があると思います．
この API を実装するべきであれば，

-   丼のサイズとその数値
-   トッピングの種類とその数値

等の対応を取得する API も必要になります．
frontEnd/backEnd 間で環境変数として共有しておけばこういった API は必要ないですが，対応付けが変わったときに困ります．

### リクエスト

-   パラメータはありません．
    -   他の対応表を取得できるようにするのであれば，対応表の種類をパラメータにする手もあります
    -   取得する対応表ごとにエンドポイントを分けても良いです．お任せします．
-   GET リクエストです．
-   エンドポイント等の指定はありません．お任せします．
    -   例えば，次のようなエンドポイントでしょうか
    -   `koujirer/amountMap`

#### 成功時
-   量を表す文字列と，それに対応する数値の辞書を BODY に含むレスポンスを返して欲しいです．
    -   key: 量の文字列
    -   value: number
    -   フォーマットはJSONでお願いします．
    -   ステータスは成功を示すものにしてください．
    -   例えばBODYは次のようです．

```yaml
{ 
    "無し": 0,
    "少なめ": 1, 
    "普通": 2, 
    "マシ": 3, 
    "マシマシ": 4 
}
```

#### 失敗時

-   簡単な失敗理由を BODY に含めたレスポンスを返して欲しいです．

### 参考資料

-   [用語定義](https://github.com/ARCircle/Kojirer/discussions/9#discussioncomment-8784803)
-   [DB スキーマ](https://www.notion.so/DB-4d6845cc5574443d86a8c9442d2f655b?pvs=4#56e4975ccaeb42d4b248a780629508cd)（3/14 参照）
-   [草案（画像，⑤）](https://github.com/ARCircle/Kojirer/discussions/9#discussioncomment-8787404)

**Comment by Atotti** [comment]
これはハードコーディングで良いですか？更新されることが無いのであれば routesが固定のjsonを返すだけで良い気がしますが

**Comment by tenk-9** [comment]
固定のJSONを返すだけでもOK（frontendの要件は満たしている）ですが，それであればそもそもAPIである必要はなくて，リポジトリのどこかに対応表に相当するjsonか何かを置いておけばいい気もします．
更新されるのはオプションの量（マシ，マシマシ，少な目，等）が増えたり減ったりするときで，強いて言えば年度が変わるときに更新されるかもしれません．

**Comment by tenk-9** [comment]
@Atotti これに関して，言葉足らずだった気がするので補足すると，
- 固定のjsonを返すようにする
- 環境変数ばりにJSONファイルをリポジトリないに用意しておく

のどちらにするかはお任せします．別の案があればそれでもかまいません．
frontendとしては，`量を表す日本語と，その数値の対応表`が得られれば（プログラムから参照できる形で手に入れば）なんでもいいです．
固定のJSONを返すのであれば，あまりバックエンドに明るくないメンバーでも実装できそうな気がしていて，タスクをまんべんなく割り振るといった意味で固定のJSONを返すエンドポイントを作るのは，大いにアリだと思います．

**Comment by woodnext** [comment]
@taniiicom  @Atotti 
この問題に関してですが，DBにテーブルをつくってしまって，フロントにわたすときにinnerJoinしちゃうほうが楽な気がしてきました．
JSONをバックエンドにおいてそれを共有するのも，各モノレポ間で密結合になるので，それもちょっとびみょい感じがします．

**Comment by woodnext** [comment]
TSの列挙型は型安全でなく，使わないほうがいいとかなんとか聞いたことがあります（[ソース](https://typescriptbook.jp/reference/values-types-variables/enum/enum-problems-and-alternatives-to-enums)）．

下記はオプションの例ですが，`enum`の代わりにオブジェクトを使うと，こんな感じでしょうか
```typescript
const Options = [ 
  "なし", 
  "少なめ", 
  "普通",
   "マシ" 
] as const;

// type OptionsType = 'なし' | '少なめ' | '普通' | 'マシ'
type OptionsType = typeof Options[keyof typeof Options];
```

これでも型安全にいけます．

**Comment by taniiicom** [comment]
オブジェクトで管理する場合, 次の 2 択だと思っています.  

### 案1

- **オプションの種類はドメイン知識として共通で扱い, 量などの詳細は擬似的に永続化層で扱う**

- **DB (prisma スキーマ) に以下の `enum` を追加し, prisma client の型定義を共通利用するのがいいと思います**

`prisma.schema`
バックエンド・フロント共通知識

```
enum Option {
  NASHI
  SUKUNAME
  FUTSU
  MASHI
}
```

↑これから生成された型を使うのがいいと思います


`API`
バックエンド -> フロント

```json
{
  "nashi": {
    "displayName": "なし",
    "amount": int,
    "price": int,
    "order": 0
  },
  "mashi": {
    "displayName": "マシ",
    "amount": int,
    "price": int,
    "order": 1
  },
  // ...
}
```

### 案2

- オプションの種類だけでなく, 詳細も含めてドメインの前提知識として, 共通知識とする

```ts
{
  nashi: {
    "displayName": "なし",
    "amount": int,
    "price": int,
    "order": 0
  },
  mashi: {
    "displayName": "マシ",
    "amount": int,
    "price": int,
    "order": 1
  },
  // ...
}
```

### notes

- DB のテーブルで管理して, join するのが本命だと思いますが, そこまでするのもコストが高そうなら, オブジェクトで管理するのがいいと思います

- @woodnext さんが言及されてるように, TS の `enum` はちょっと癖があるので, TS の中で完結する形で使うなら`UnionType` の方が良いと思います

- ただ, `UnionType` は順序性を扱えないのと, これとは別に, 上の議論でされてるような辞書構造orテーブル構造が結局必要になると思うので, それならやはり上で議論されていたように, オブジェクトをオリジンとして, オプションに関する情報はそちらで管理するのもありだと思います

- JS のオブジェクトは, json とちがって, key は文字列もリテラルも同じものとして扱わられるので, TS なら key に対するインテリセンスも効きますし上で言及されていた需要は満たせると思います

**Comment by woodnext** [comment]
なんだかDBのテーブルで管理するのが丸い気がしてきましたね...

**Comment by Atotti** [comment]
ここだけに関して言えばオブジェクトで管理の案1が良いかなーという気がしますが、DBに保存するのであれば、「GETするAPI」と「設定する管理画面」と「設定をPOSTするAPI」を実装することになりそうですかね。

これに限らず、個人的にはDBを諸々操作するための[ActiveAdmin](https://qiita.com/MariMurotani/items/aed93986e29249fd65e5)のような管理画面はどこかで必要になりそう、というかあったほうが良い思っていて、作っちゃっても良いと思います。

ところで、Express ✖️ prisma に ActiveAdmin, DjangoAdmin, phpMyAdminのような管理画面生せるライブラリってあったりするんでしょうか？あったらそれ使うのが良さそう。

**Comment by woodnext** [comment]
> ところで、Express ✖️ prisma に ActiveAdmin, DjangoAdmin, phpMyAdminのような管理画面生せるライブラリってあったりするんでしょうか？あったらそれ使うのが良さそう。

Prismaが提供しているもので，(Prisma Studio)[https://www.prisma.io/studio] というものがあります．
Active Adminを置き換えるものかどうかはわかりませんが．

**Comment by Atotti** [comment]
今読み直したけど、案1のようにDBに入れるのが良さそう。
結局のところここ以外でも、`toppings`などはDBにラベルとidの対応関係を直接入れる必要があるので、管理画面は必要そうな気がしています。（prisma経由で直接クエリ叩くこともできるが、良くはない思う。）

ちょっと調べた感じ、prisma Studioか、[Admin.js](https://adminjs.co/) あたりが良さそう

**Comment by Atotti** [comment]
```yaml
/options:
  get:
    response:
      '200':
        description: オプションの数字と言葉をマッピングを取得
       content:
         applicaoin/json:
           schema:
           type: array
             items: 
               $ref: '#hoge/Option'
Option:
  type: object
    # これレスポンスなんだ？
```
