### ISSUE TITLE
丼の値段を取得するAPIの実装

### ISSUE THREAD

**Issue by 4416kidr** [ARCircle/Kojirer#19]
# 丼の値段を取得するAPIの実装

## 機能

- 顧客が注文を確定する前に金額を確認できるようにするために必要
- 丼の情報を送ると値段が返ってくる

## request

- GETメソッドで丼の情報を送る。具体的には以下
  - size: 麺の多さ
  - topping: 具材の上に乗っける調味料
    - 年度によって変わりうるが、2023年度の内容で考える
    - (mayo, carry, pepper, ra-yu, lemon)
  - sns_followed: SNSをフォローしているかどうか
    - 23年度の場合、SNSをフォローしていると50引きだったらしい
- APIの例
  - GET /price?size=2&mayo=1
    - 麺の多さが2でマヨの多さが1
  - GET /price?size=1&carry=2
    - 麺の多さが1でカレーの多さが2
  - GET /price?size=1&lemon=1&sns_followed=1
    - 麺の多さが1でレモンの多さが1でSNSをフォローしているので50円引き

## response

- {price: 500}

**Comment by woodnext** [comment]
@tenk-9 @4416kidr 
GETのクエリパラメータがオブジェクト扱えないので，パラメータの型に苦戦しそうです．
POSTリクエストならオブジェクトを入れれるので，GETからPOSTにするという手があります．
検討お願いします．

**Comment by tenk-9** [comment]
POSTリクエストにするの，良いと思います
