### ISSUE TITLE
docker composeにsudoが必要な問題を解決したい

### ISSUE THREAD

**Issue by woodnext** [ARCircle/Kojirer#2]
volumesの権限がrootのせいでうまくいってない

**Comment by 4416kidr** [comment]
私の環境では、特にsudoしなくてもいけました。
何故かわからないのですが…

**Comment by 4416kidr** [comment]
.devcontainerに移行したので、このイシューは不要である可能性があると思います。

**Comment by woodnext** [comment]
そうですね。
クローズにしたいと思います。
