### ISSUE TITLE
改行コードの統一

### ISSUE THREAD

**Issue by 4416kidr** [ARCircle/Kojirer#20]
プロジェクト内に複数の改行コードが混在しており、改行コードの変更がdiffで表示されてしまう。

**Comment by woodnext** [comment]
基本的にwslやlinux, macos(OS X以降)等，unix系環境で作業する想定なので，改行コードはLFに統一したいです．
[この記事](https://zenn.dev/gekal/articles/git-line-endings-practices)によると，`.gitattributes`という設定ファイルを作ることで，各々で設定などせず，解決できるようです．

**Comment by woodnext** [comment]
一応すべてLFに変更できましたので，確認をお願いします．
