### ISSUE TITLE
[backend] `util`と`utils`が混在している

### ISSUE THREAD

**Issue by hikuohiku** [ARCircle/Kojirer#47]
今気づいたんですが，`/packages/backend/src/util` と `/packages/backend/src/utils`で同じ役割のディレクトリが重複して存在してしまってますね．

## 解決策
- どちらか要らない方を消す，個人的には原本を尊重して`util`を残せば良い気がしています

## 経緯
経緯もあたりがついていて，
-  @taniiicom が #39 で`/src/util`の方を作成してくれていた
- 自分がそのPRがマージされる前に #38 でその差分を使いたくてチェリーピックした
- そこでNode組み込みのutilモジュールを使おうとすると，`/src/util`と名前衝突してうまくいかなかった．
- ので，`/src/util` -> `/src/utils` に名前変更するコミットを入れた（ https://github.com/ARCircle/Kojirer/pull/38/commits/747cd90dc6710b28c975fd95dd01d060f6e079b9 ）
- 名前を変更するコミットを含む自分のPR #38 がマージされた
- 原本の（名前変更のない） #39 がマージされた

という経緯で重複しているような気がします．

ここでなんかおかしいことが起きていて，どうもコミットの差分を見ると別に名前衝突しなそうに見えます．
```typescript
import prisma from '@/lib/prismaClient.js';
// import { bigint2number } from '@/util/typeConverters.js'; // 変更前
import { bigint2number } from '@/utils/typeConverters.js';
import express from 'express';
import util from 'util';
```

実際僕の今の環境でlinterにかけても特に怒られないので，必要ない差分だった可能性が高いです．
確かにエラー出てた気がするんですが，おかしなこともあるもんですね．ご迷惑おかけしました．

**Comment by taniiicom** [comment]
そういえばそんな経緯あったね
思い出した

`util` の競合については, tsconfig のモジュールパターンによるものかもね

**Comment by hikuohiku** [comment]
そのうち修正PR出したいと思います

**Comment by taniiicom** [comment]
たしかキジさんの最新の PR で修正されてたはず

**Comment by hikuohiku** [comment]
majidesuka

**Comment by taniiicom** [comment]
https://github.com/ARCircle/Kojirer/pull/46
これかな

**Comment by woodnx** [comment]
@taniiicom @hikuohiku 
個人的には、複数形の方がいいと思ってutilsにした感じです。
勝手に消しちゃってすみません...

**Comment by hikuohiku** [comment]
むしろ修正していただいてありがとうございます、ご迷惑おかけしました！
